# Generated by Django 5.0.3 on 2024-12-25 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('describtion', models.CharField(max_length=900, null=True)),
                ('image', models.ImageField(upload_to='static/threshold/models/img/')),
            ],
        ),
        migrations.CreateModel(
            name='Image_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='static/threshold/img/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='threshold_element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area1', models.CharField(blank=True, default='x', max_length=200)),
                ('cam_ip1', models.CharField(blank=True, default='x', max_length=900)),
                ('area2', models.CharField(blank=True, default='x', max_length=200)),
                ('cam_ip2', models.CharField(blank=True, default='x', max_length=900)),
                ('area3', models.CharField(blank=True, default='x', max_length=200)),
                ('cam_ip3', models.CharField(blank=True, default='x', max_length=900)),
                ('area4', models.CharField(blank=True, default='x', max_length=200)),
                ('cam_ip4', models.CharField(blank=True, default='x', max_length=900)),
                ('area5', models.CharField(blank=True, default='x', max_length=200)),
                ('cam_ip5', models.CharField(blank=True, default='x', max_length=900)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, upload_to='static/threshold/video/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
