# Generated by Django 5.0.3 on 2024-12-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0002_threshold_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold_component',
            name='area1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='threshold_component',
            name='area2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='threshold_component',
            name='area3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='threshold_component',
            name='area4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='threshold_component',
            name='area5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='threshold_component',
            name='cam_ip1',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='threshold_component',
            name='cam_ip2',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='threshold_component',
            name='cam_ip3',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='threshold_component',
            name='cam_ip4',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='threshold_component',
            name='cam_ip5',
            field=models.CharField(blank=True, max_length=900),
        ),
    ]
