# Generated by Django 5.0.3 on 2024-12-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0003_alter_threshold_component_area1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='threshold_component',
        ),
    ]
