# Generated by Django 5.0.3 on 2024-12-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0005_threshold_component'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threshold_element',
            name='user',
        ),
        migrations.DeleteModel(
            name='threshold_component',
        ),
        migrations.DeleteModel(
            name='threshold_element',
        ),
    ]
