# Generated by Django 5.0.3 on 2024-12-26 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0007_threshold_component_threshold_element'),
    ]

    operations = [
        migrations.DeleteModel(
            name='threshold_element',
        ),
    ]
