# Generated by Django 5.0.3 on 2025-01-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0009_yolo_model_threshold_component_yolo_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threshold_component',
            name='yolo_model',
        ),
    ]
