# Generated by Django 5.0.3 on 2025-01-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0010_remove_threshold_component_yolo_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Yolo_model',
        ),
    ]
