# Generated by Django 5.0.3 on 2025-01-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0011_delete_yolo_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yolo_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model_file', models.FileField(default='static/threshold/models/yolo11n.pt', upload_to='static/threshold/models')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
