# Generated by Django 5.0.3 on 2025-01-09 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0012_yolo_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yolo_model',
            options={'verbose_name_plural': 'Yolo_Models'},
        ),
        migrations.AddField(
            model_name='threshold_component',
            name='yolo_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='threshold.yolo_model'),
            preserve_default=False,
        ),
    ]
