# Generated by Django 5.0.3 on 2025-01-09 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0013_alter_yolo_model_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold_component',
            name='yolo_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threshold.model_info'),
        ),
        migrations.DeleteModel(
            name='Yolo_model',
        ),
    ]
