# Generated by Django 5.0.3 on 2025-01-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0014_alter_threshold_component_yolo_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threshold_component',
            name='yolo_model',
        ),
    ]
