# Generated by Django 5.0.3 on 2025-01-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0015_remove_threshold_component_yolo_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='yolo_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'yolo_model',
            },
        ),
    ]
