# Generated by Django 5.0.3 on 2025-01-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0017_threshold_component_model1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yolo_model',
            name='name',
            field=models.IntegerField(max_length=30),
        ),
    ]
