# Generated by Django 5.0.3 on 2025-01-11 08:51

import django.db.models.deletion
import threshold.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0027_alter_threshold_component_model1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold_component',
            name='model1',
            field=models.ForeignKey(default=threshold.models.yolo_model.get_default_pk, on_delete=django.db.models.deletion.CASCADE, related_name='ip_cam_1_model', to='threshold.yolo_model'),
        ),
    ]
