# Generated by Django 5.0.3 on 2025-01-11 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0029_alter_threshold_component_model1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold_component',
            name='model1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_cam_1_model', to='threshold.yolo_model'),
        ),
    ]
