# Generated by Django 5.0.3 on 2025-01-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0032_alter_threshold_component_model1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threshold_component',
            name='cam1_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='threshold_component',
            name='cam2_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='threshold_component',
            name='cam3_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='threshold_component',
            name='cam4_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='threshold_component',
            name='cam5_active',
            field=models.BooleanField(default=False),
        ),
    ]
